"""
用 Python 版 LDN 的真实加密代码生成对拍向量，写成 Rust 常量文件，供 ldn-crypto 使用。

覆盖：KeyDerivation（协议 1 与 3 的三种派生密钥）、数据帧 CCMP、广播帧 AES-CTR /
AES-GCM、认证帧 AES-GCM、挑战 HMAC。所有“系统密钥”都是脚本里写死的假值，
不需要也不应该使用真实的 prod.keys。

准备环境见 gen_python_vectors.py。用法:
    .venv/bin/python tools/gen_crypto_vectors.py <Python 版 LDN 仓库路径>

取值必须与 crates/ldn-crypto/tests/python_parity.rs 一致。
"""

import hmac
import pathlib
import sys

# 假的 prod.keys 内容：只包含派生所需的四把，值为固定的可识别字节。
FAKE_KEYS = {
    "master_key_00": bytes(range(0x00, 0x10)),
    "master_key_12": bytes(range(0x10, 0x20)),
    "aes_kek_generation_source": bytes(range(0x20, 0x30)),
    "aes_key_generation_source": bytes(range(0x30, 0x40)),
}
CLIENT_RANDOM = bytes(range(0x40, 0x50))
SERVER_RANDOM = bytes(range(0x50, 0x60))
PASSWORD = b"LunchPack2DefaultPhrase"
ADV_NONCE = bytes.fromhex("01020304")
PLAINTEXT = b"LDN crypto parity plaintext, longer than one AES block."
AUTH_HEADER = bytes(range(0x60, 0x60 + 0x48))
HMAC_DATA = b"challenge body"
CCMP_KEY = bytes(range(0x70, 0x80))


def build_vectors(ldn, wlan) -> dict[str, bytes]:
    v = {}
    keys_text = "".join(f"{k} = {val.hex()}\n" for k, val in FAKE_KEYS.items())
    v["KEYS_FILE"] = keys_text.encode()

    for protocol in (1, 3):
        kd = ldn.KeyDerivation(FAKE_KEYS, protocol)
        p = f"P{protocol}"
        v[f"{p}_AUTH_KEY"] = kd.derive_authentication_key(CLIENT_RANDOM)
        v[f"{p}_DATA_KEY"] = kd.derive_data_key(SERVER_RANDOM, PASSWORD)

        adv = ldn.AdvertisementFrame(kd, protocol)
        adv.nonce = ADV_NONCE
        v[f"{p}_ADV_KEY_DATA"] = adv.network_id.encode(">")
        v[f"{p}_ADV_KEY"] = adv._derive_key()
        v[f"{p}_ADV_CTR"] = adv._encrypt_aes_ctr(PLAINTEXT)
        # _encrypt_aes_gcm 返回 tag + 密文。
        v[f"{p}_ADV_GCM"] = adv._encrypt_aes_gcm(AUTH_HEADER[:0x28], PLAINTEXT)

        auth = ldn.AuthenticationFrame(kd, protocol)
        auth.client_random = CLIENT_RANDOM
        ciphertext, tag = auth._encrypt_aes_gcm(AUTH_HEADER, PLAINTEXT)
        v[f"{p}_AUTH_GCM_CT"] = ciphertext
        v[f"{p}_AUTH_GCM_TAG"] = tag

    v["CHALLENGE_KEY"] = ldn.CHALLENGE_KEY
    v["CHALLENGE_KEY_DEV"] = ldn.CHALLENGE_KEY_DEV
    v["HMAC_PROD"] = hmac.digest(ldn.CHALLENGE_KEY, HMAC_DATA, "sha256")

    frame = wlan.DataFrame(
        target=wlan.MACAddress("ff:ff:ff:ff:ff:ff"),
        source=wlan.MACAddress("02:00:00:00:00:01"),
        bssid=wlan.MACAddress("02:00:00:00:00:01"),
        fromds=True,
        payload=PLAINTEXT,
    )
    frame.encrypt(CCMP_KEY, packetno=0x0000AABBCCDD, keyid=1)
    v["CCMP_ENCRYPTED_FRAME"] = frame.encode()
    return v


def render_rust(vectors: dict[str, bytes], source: str) -> str:
    lines = ["// @generated by tools/gen_crypto_vectors.py -- 不要手改。",
             f"// 来源: Python LDN {source}；所有系统密钥均为假值。", ""]
    for name, data in vectors.items():
        lines.append(f'pub const {name}: &str = "{data.hex()}";')
    return "\n".join(lines) + "\n"


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    repo = pathlib.Path(sys.argv[1]).resolve()
    sys.path.insert(0, str(repo))
    import ldn
    from ldn import wlan

    out = pathlib.Path(__file__).resolve().parent.parent / \
        "crates/ldn-crypto/tests/vectors/python_crypto_vectors.rs"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_rust(build_vectors(ldn, wlan), repo.name))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
