"""
从 Python 版 LDN 生成字节级黄金向量，写成 Rust 常量文件，供 ldn-wire 的对拍测试使用。

准备环境（只需一次）:
    python3 -m venv .venv
    .venv/bin/pip install -r tools/requirements.txt

用法:
    .venv/bin/python tools/gen_python_vectors.py <Python 版 LDN 仓库路径>

Python 端的字段取值必须与 crates/ldn-wire/tests/python_parity.rs 里构造的
结构体逐一对应，改一边就要改另一边。
"""

import pathlib
import sys


# CCMP 向量用的固定 128 位密钥，只用于测试。
CCMP_TEST_KEY = bytes(range(0x10, 0x20))


def build_vectors(wlan) -> dict[str, bytes]:
    """按固定输入调用 Python 编码器，返回 常量名 -> 编码结果。"""
    a = wlan.MACAddress("02:00:00:00:00:01")
    b = wlan.MACAddress("02:00:00:00:00:02")
    bc = wlan.MACAddress("ff:ff:ff:ff:ff:ff")
    ies = {0: b"ldn", 3: b"\x06"}

    v = {}
    v["ELEMENTS"] = wlan.encode_elements(
        {3: b"\x06", 0: b"ldn", 1: b"\x82\x84\x8b\x96"}
    )
    v["RSN_ELEMENT"] = wlan.RSNElement(
        wlan.WLAN_CIPHER_SUITE_CCMP, [wlan.WLAN_CIPHER_SUITE_CCMP],
        [wlan.WLAN_AKM_SUITE_PSK], 0x000C
    ).encode()
    v["RADIOTAP_BASIC"] = wlan.RadiotapFrame(
        data=b"\xde\xad", flags=0x10, rate=2, frequency=2437,
        channel_flags=0x00A0
    ).encode()
    v["RADIOTAP_MACTIME"] = wlan.RadiotapFrame(
        data=b"\x01", mactime=0x0102030405060708, flags=0
    ).encode()
    v["MAC_HEADER"] = wlan.MACHeader(
        type=2, subtype=0, flags=0x42, duration=0x1234,
        address1=a, address2=b, address3=bc, sequence_control=0x5670
    ).encode()
    v["ASSOCIATION_REQUEST"] = wlan.AssociationRequest(
        a, b, 0x0421, 10, {0: b"ldn"}
    ).encode()
    v["ASSOCIATION_RESPONSE"] = wlan.AssociationResponse(
        b, a, 0x0421, 0, 0xC001, {1: b"\x82"}
    ).encode()
    v["PROBE_REQUEST"] = wlan.ProbeRequest(b, {0: b""}).encode()
    v["PROBE_RESPONSE"] = wlan.ProbeResponse(
        b, a, 0x1122334455667788, 100, 0x0421, ies
    ).encode()
    v["BEACON"] = wlan.BeaconFrame(a, 0, 100, 0x0421, ies).encode()
    v["AUTHENTICATION"] = wlan.AuthenticationFrame(a, b, a, 0, 1, 0).encode()
    v["DEAUTHENTICATION"] = wlan.DeauthenticationFrame(a, b, a, 3).encode()
    v["ACTION"] = wlan.ActionFrame(a, b"\x7f\x00\x22\xaa\x04\x01").encode()

    snap = wlan.SNAPHeader(0, 0x0800, b"hello").encode()
    v["SNAP"] = snap
    v["DATA_PLAIN"] = wlan.DataFrame(
        target=bc, source=a, bssid=a, fromds=True, payload=snap
    ).encode()
    protected = wlan.DataFrame(
        target=bc, source=a, bssid=a, fromds=True, protected=True,
        nonce=0x123456789ABC, keyid=1, payload=bytes(range(1, 10))
    )
    v["DATA_PROTECTED"] = protected.encode()
    v["CCMP_NONCE"] = protected._nonce()
    v["CCMP_AAD"] = protected._aad()

    # 真实 AES-CCM 加密后的帧：阶段 1 只用来校验头部解析，阶段 2 接入加密后用来对拍密文。
    encrypted = wlan.DataFrame(
        target=bc, source=a, bssid=a, fromds=True, payload=snap
    )
    encrypted.encrypt(CCMP_TEST_KEY, packetno=1, keyid=1)
    v["CCMP_TEST_KEY"] = CCMP_TEST_KEY
    v["DATA_CCMP_ENCRYPTED"] = encrypted.encode()

    v["ETHERNET"] = wlan.EthernetFrame(bc, a, 0x0806, b"arp").encode()
    return v


def render_rust(vectors: dict[str, bytes], source: str) -> str:
    lines = [
        "// @generated by tools/gen_python_vectors.py -- 不要手改。",
        f"// 来源: Python LDN {source}",
        "",
    ]
    for name, data in vectors.items():
        lines.append(f'pub const {name}: &str = "{data.hex()}";')
    return "\n".join(lines) + "\n"


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    python_repo = pathlib.Path(sys.argv[1]).resolve()
    sys.path.insert(0, str(python_repo))
    from ldn import wlan

    out = pathlib.Path(__file__).resolve().parent.parent / \
        "crates/ldn-wire/tests/vectors/python_vectors.rs"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_rust(build_vectors(wlan), python_repo.name))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
